#!/usr/bin/env bash
set -euo pipefail

# Setup LiteLLM proxy with free API round-robin
# Run this on the machine that will host the LiteLLM proxy.
# See ../free-ai-providers.md for signup links.

LITELLM_DIR="${LITELLM_DIR:-$HOME}"
LITELLM_PORT="${LITELLM_PORT:-4000}"
LITELLM_MASTER_KEY="${LITELLM_MASTER_KEY:-sk-litellm-local}"
VENV_DIR="${LITELLM_DIR}/litellm-venv"
CONFIG_FILE="${LITELLM_DIR}/litellm-config.yaml"
ENV_FILE="${LITELLM_DIR}/.litellm.env"

info()  { echo -e "\033[1;34m==>\033[0m $*"; }
ok()    { echo -e "\033[1;32m  ✓\033[0m $*"; }
warn()  { echo -e "\033[1;33m  !\033[0m $*"; }
err()   { echo -e "\033[1;31m  ✗\033[0m $*" >&2; }

# ── Check prerequisites ──────────────────────────────────────────────

info "Checking prerequisites..."

if ! command -v python3 &>/dev/null; then
    err "python3 not found. Install Python 3.11+ first."
    exit 1
fi

if ! python3 -c "import venv" &>/dev/null; then
    err "python3-venv is required but not installed."
    err "Install it: sudo apt install python3-venv  (or equivalent for your distro)"
    exit 1
fi

PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJOR=$(echo "$PY_VER" | cut -d. -f1)
PY_MINOR=$(echo "$PY_VER" | cut -d. -f2)
if [ "$PY_MAJOR" -lt 3 ] || ([ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 11 ]); then
    warn "Python $PY_VER detected. Python 3.11+ recommended."
fi

ok "Python $PY_VER"

# ── Create virtual environment ────────────────────────────────────────

info "Setting up virtual environment at ${VENV_DIR}..."

if [ -d "$VENV_DIR" ]; then
    warn "Venv already exists at ${VENV_DIR}, reusing."
else
    python3 -m venv "$VENV_DIR"
    ok "Created venv"
fi

source "${VENV_DIR}/bin/activate"

info "Installing LiteLLM..."
pip install --quiet 'litellm[proxy]' 'fastapi<0.116.0'
ok "LiteLLM installed ($(pip show litellm 2>/dev/null | grep Version | cut -d' ' -f2))"

# ── Detect API keys from environment ─────────────────────────────────

info "Scanning environment for API keys..."

GEMINI_KEYS=""
GROQ_KEYS=""
MISTRAL_KEYS=""
CEREBRAS_KEYS=""
OPENROUTER_KEYS=""
DEEPSEEK_KEYS=""
DEEPINFRA_KEYS=""
CLOUDFLARE_KEYS=""
COHERE_KEYS=""
NVIDIA_KEYS=""
POLLINATIONS_KEYS=""
OPENAI_KEYS=""
FOUND_KEYS=0
FOUND_PROVIDERS=0

scan_key() {
    local var_name="$1"
    local provider_var="$2"
    if [ -n "${!var_name:-}" ]; then
        eval "${provider_var}=\"\${${provider_var}} ${var_name}\""
        FOUND_KEYS=$((FOUND_KEYS + 1))
        ok "$var_name"
    fi
}

for var in GOOGLE_API_KEY GOOGLE_API_KEY_{2..10}; do scan_key "$var" "GEMINI_KEYS"; done
for var in GROQ_API_KEY GROQ_API_KEY_{2..10}; do scan_key "$var" "GROQ_KEYS"; done
for var in MISTRAL_API_KEY MISTRAL_API_KEY_{2..10}; do scan_key "$var" "MISTRAL_KEYS"; done
for var in CEREBRAS_API_KEY CEREBRAS_API_KEY_{2..10}; do scan_key "$var" "CEREBRAS_KEYS"; done
for var in OPENROUTER_API_KEY OPENROUTER_API_KEY_{2..10}; do scan_key "$var" "OPENROUTER_KEYS"; done
for var in DEEPSEEK_API_KEY DEEPSEEK_API_KEY_{2..10}; do scan_key "$var" "DEEPSEEK_KEYS"; done
for var in DEEPINFRA_API_KEY DEEPINFRA_API_KEY_{2..10}; do scan_key "$var" "DEEPINFRA_KEYS"; done
for var in CLOUDFLARE_API_KEY CLOUDFLARE_API_KEY_{2..10}; do scan_key "$var" "CLOUDFLARE_KEYS"; done
if [ -n "${CLOUDFLARE_ACCOUNT_ID:-}" ]; then ok "CLOUDFLARE_ACCOUNT_ID"; fi
for var in COHERE_API_KEY COHERE_API_KEY_{2..10}; do scan_key "$var" "COHERE_KEYS"; done
for var in NVIDIA_API_KEY NVIDIA_API_KEY_{2..10}; do scan_key "$var" "NVIDIA_KEYS"; done
for var in POLLINATIONS_API_KEY POLLINATIONS_API_KEY_{2..10}; do scan_key "$var" "POLLINATIONS_KEYS"; done
for var in OPENAI_API_KEY OPENAI_API_KEY_{2..10}; do scan_key "$var" "OPENAI_KEYS"; done

for prov in GEMINI_KEYS GROQ_KEYS MISTRAL_KEYS CEREBRAS_KEYS OPENROUTER_KEYS DEEPSEEK_KEYS DEEPINFRA_KEYS CLOUDFLARE_KEYS COHERE_KEYS NVIDIA_KEYS POLLINATIONS_KEYS OPENAI_KEYS; do
    if [ -n "${!prov:-}" ]; then FOUND_PROVIDERS=$((FOUND_PROVIDERS + 1)); fi
done

if [ "$FOUND_KEYS" -eq 0 ]; then
    warn "No API keys found in environment."
    warn "Export your API keys in ~/.bashrc first, then re-run this script."
    warn "See ../free-ai-providers.md for signup links and env var names."
    exit 1
fi

info "Found $FOUND_KEYS API keys across $FOUND_PROVIDERS providers."

# ── Generate litellm-config.yaml ─────────────────────────────────────

info "Generating ${CONFIG_FILE}..."

if [ -f "$CONFIG_FILE" ]; then
    cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"
    warn "Backed up existing config to ${CONFIG_FILE}.bak"
fi

cat > "$CONFIG_FILE" << 'HEADER'
# Auto-generated by setup-litellm.sh
# See https://github.com/FlossWare/crush/blob/main/litellm-setup.md

model_list:
HEADER

IDX=0

add_model() {
    local model_name="$1"
    local litellm_model="$2"
    local env_var="$3"
    local id_prefix="$4"
    ((IDX++))
    cat >> "$CONFIG_FILE" << EOF
  - model_name: ${model_name}
    litellm_params:
      model: ${litellm_model}
      api_key: os.environ/${env_var}
    model_info:
      id: ${id_prefix}-${IDX}
EOF
}

add_model_custom_base() {
    local model_name="$1"
    local litellm_model="$2"
    local api_base="$3"
    local env_var="$4"
    local id_prefix="$5"
    ((IDX++))
    cat >> "$CONFIG_FILE" << EOF
  - model_name: ${model_name}
    litellm_params:
      model: ${litellm_model}
      api_base: ${api_base}
      api_key: os.environ/${env_var}
    model_info:
      id: ${id_prefix}-${IDX}
EOF
}

# Generate entries per provider
for key_var in $GEMINI_KEYS; do
    add_model "gemini-3.5-flash" "gemini/gemini-3.5-flash" "$key_var" "gemini-flash"
done

for key_var in $GROQ_KEYS; do
    add_model "llama-3.3-70b" "groq/llama-3.3-70b-versatile" "$key_var" "groq-llama"
done

for key_var in $MISTRAL_KEYS; do
    add_model "mistral-small" "mistral/mistral-small-latest" "$key_var" "mistral-small"
    add_model "codestral" "mistral/codestral-latest" "$key_var" "codestral"
done

for key_var in $CEREBRAS_KEYS; do
    add_model "cerebras-llama" "cerebras/llama-3.3-70b" "$key_var" "cerebras"
done

for key_var in $OPENROUTER_KEYS; do
    add_model "nemotron-ultra" "openrouter/nvidia/nemotron-3-ultra-550b-a55b:free" "$key_var" "or-nemotron"
    add_model "gemma-4-31b" "openrouter/google/gemma-4-31b-it:free" "$key_var" "or-gemma"
done

for key_var in $DEEPSEEK_KEYS; do
    add_model "deepseek-chat" "deepseek/deepseek-chat" "$key_var" "deepseek"
done

for key_var in $DEEPINFRA_KEYS; do
    add_model "deepinfra-llama" "deepinfra/meta-llama/Llama-3.3-70B-Instruct" "$key_var" "deepinfra"
done

for key_var in $CLOUDFLARE_KEYS; do
    if [ -n "${CLOUDFLARE_ACCOUNT_ID:-}" ]; then
        add_model_custom_base "cloudflare" \
            "openai/@cf/meta/llama-3.3-70b-instruct-fp8-fast" \
            "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/v1" \
            "$key_var" "cf"
    else
        warn "Skipping Cloudflare: CLOUDFLARE_ACCOUNT_ID not set"
    fi
done

for key_var in $COHERE_KEYS; do
    add_model "command-r" "cohere/command-r" "$key_var" "cohere"
done

for key_var in $NVIDIA_KEYS; do
    add_model "nvidia-llama" "nvidia_nim/meta/llama-3.3-70b-instruct" "$key_var" "nvidia"
done

for key_var in $POLLINATIONS_KEYS; do
    add_model_custom_base "pollinations" \
        "openai/openai-fast" \
        "https://text.pollinations.ai/openai" \
        "$key_var" "pollinations"
done

for key_var in $OPENAI_KEYS; do
    add_model "gpt-4o-mini" "gpt-4o-mini" "$key_var" "openai"
done

# Build fallback list from available providers
FALLBACK_PRIMARY=""
FALLBACK_MODELS=""
[ -n "$GEMINI_KEYS" ]    && FALLBACK_PRIMARY="gemini-3.5-flash" && FALLBACK_MODELS="gemini-3.5-flash"
[ -n "$GROQ_KEYS" ]      && FALLBACK_MODELS="$FALLBACK_MODELS llama-3.3-70b"
[ -n "$MISTRAL_KEYS" ]   && FALLBACK_MODELS="$FALLBACK_MODELS mistral-small"
[ -n "$CEREBRAS_KEYS" ]  && FALLBACK_MODELS="$FALLBACK_MODELS cerebras-llama"
[ -n "$DEEPSEEK_KEYS" ]  && FALLBACK_MODELS="$FALLBACK_MODELS deepseek-chat"

FALLBACK_MODELS=$(echo "$FALLBACK_MODELS" | xargs)

# Use first available as primary if no Gemini
if [ -z "$FALLBACK_PRIMARY" ] && [ -n "$FALLBACK_MODELS" ]; then
    FALLBACK_PRIMARY=$(echo "$FALLBACK_MODELS" | awk '{print $1}')
fi

FALLBACK_COUNT=$(echo "$FALLBACK_MODELS" | wc -w)

# Write settings
cat >> "$CONFIG_FILE" << EOF

litellm_settings:
  num_retries: 3
  request_timeout: 60
  set_verbose: false
  drop_params: true
EOF

# Write fallbacks if we have more than one model
if [ "$FALLBACK_COUNT" -gt 1 ]; then
    echo "  fallbacks:" >> "$CONFIG_FILE"
    for model in $FALLBACK_MODELS; do
        echo "    - ${model}:" >> "$CONFIG_FILE"
        for fallback in $FALLBACK_MODELS; do
            if [ "$fallback" != "$model" ]; then
                echo "      - ${fallback}" >> "$CONFIG_FILE"
            fi
        done
    done
fi

cat >> "$CONFIG_FILE" << EOF

router_settings:
  routing_strategy: simple-shuffle
  allowed_fails: 3
  cooldown_time: 30
  retry_after: 5

general_settings:
  master_key: ${LITELLM_MASTER_KEY}
  database_url: null
EOF

ok "Generated config with $IDX model entries"

# ── Generate env file for systemd ─────────────────────────────────────

info "Generating env file at ${ENV_FILE}..."

# Extract exports from bashrc, strip 'export' and quotes
if [ -f "$HOME/.bashrc" ]; then
    grep "^export " "$HOME/.bashrc" \
        | grep -E "(_API_KEY|CLOUDFLARE_ACCOUNT_ID)=" \
        | sed "s/^export //" \
        | sed "s/['\"]//g" \
        > "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    ENVCOUNT=$(wc -l < "$ENV_FILE")
    ok "Wrote $ENVCOUNT env vars to ${ENV_FILE}"
else
    warn "No ~/.bashrc found — create ${ENV_FILE} manually with your API keys"
fi

# ── Create systemd service ────────────────────────────────────────────

LITELLM_BIN="${VENV_DIR}/bin/litellm"

if ! command -v systemctl &>/dev/null; then
    warn "Systemd not detected. Skipping service creation."
    echo ""
    info "Start LiteLLM manually:"
    echo "  ${LITELLM_BIN} --config ${CONFIG_FILE} --host 0.0.0.0 --port ${LITELLM_PORT}"
    echo ""
    info "Setup complete (manual mode)!"
    echo "  Config:   ${CONFIG_FILE}"
    echo "  Env file: ${ENV_FILE}"
    exit 0
fi

info "Creating systemd service..."

SERVICE_FILE="/etc/systemd/system/litellm.service"

if [ -f "$SERVICE_FILE" ]; then
    warn "Service file already exists at ${SERVICE_FILE}"
    read -rp "    Overwrite? [y/N] " ans
    if [[ ! "$ans" =~ ^[Yy] ]]; then
        warn "Skipping service creation."
        info "Start manually: ${LITELLM_BIN} --config ${CONFIG_FILE} --host 0.0.0.0 --port ${LITELLM_PORT}"
        exit 0
    fi
fi

sudo tee "$SERVICE_FILE" > /dev/null << EOF
[Unit]
Description=LiteLLM Proxy - Free API Round-Robin
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$(whoami)
Group=$(id -gn)
WorkingDirectory=${LITELLM_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=${LITELLM_BIN} --config ${CONFIG_FILE} --host 0.0.0.0 --port ${LITELLM_PORT}
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable litellm
ok "Created and enabled litellm.service"

# ── Start the service ─────────────────────────────────────────────────

info "Starting LiteLLM (this takes ~50 seconds)..."
sudo systemctl start litellm

# Wait for startup
for i in $(seq 1 60); do
    if curl -sf "http://localhost:${LITELLM_PORT}/health" &>/dev/null; then
        ok "LiteLLM is running on port ${LITELLM_PORT}"
        break
    fi
    if [ "$i" -eq 60 ]; then
        err "LiteLLM failed to start within 60 seconds."
        err "Check logs: journalctl -u litellm -n 50"
        exit 1
    fi
    sleep 1
done

# ── Verify ────────────────────────────────────────────────────────────

info "Verifying..."

MODEL_COUNT=$(curl -sf "http://localhost:${LITELLM_PORT}/v1/models" \
    -H "Authorization: Bearer ${LITELLM_MASTER_KEY}" \
    | python3 -c "import json,sys; print(len(json.load(sys.stdin).get('data',[])))" 2>/dev/null || echo "0")

if [ "$MODEL_COUNT" -gt 0 ]; then
    ok "$MODEL_COUNT models available"
else
    warn "Could not list models — check logs: journalctl -u litellm -n 50"
fi

echo ""
info "Setup complete!"
echo "  Config:     ${CONFIG_FILE}"
echo "  Env file:   ${ENV_FILE}"
echo "  Service:    systemctl status litellm"
echo "  Logs:       journalctl -u litellm -f"
echo "  Test:       curl http://localhost:${LITELLM_PORT}/v1/models -H 'Authorization: Bearer ${LITELLM_MASTER_KEY}'"
echo ""
echo "  Next: run setup-crush.sh on each machine that needs Crush."
